### ISSUE TITLE
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api.uberduck.ai:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')]

### ISSUE THREAD

**Issue by birds1338** [ImNimboss/uberduck#1]
## Description

SSL Issue
`aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api.uberduck.ai:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')]`

## Reproduction steps

Unclear.

## Uberduck version

0.0.1

## Operating system & Python Version

Windows 11 22H2 (22581.1)
Python 3.10

**Comment by ImNimboss** [comment]
This isn't an uberduck problem. I'll try to help you out using linked resources but otherwise I'm fairly unfamiliar with this error.

**Comment by ImNimboss** [comment]
@birds1338 Go to your Python 3.10 folder. Is there a file called `Install Certificates.command`? If so then open it and your issue should be resolved
