### ISSUE TITLE
Trying to install pip install 0.0.3 always fails

### ISSUE THREAD

**Issue by cool-cose** [ImNimboss/uberduck#2]
no matter what I do I get this error, both on Mac and windows. I've tried everything I could think of.
installing 0.0.1 works fine but its out-dated and the documentation that's on here doesn't completely work with it

please. help.

![image](https://user-images.githubusercontent.com/84683778/208621800-a3b29b47-63ad-44e0-9b14-3ecfba9898ea.png)

**Comment by ImNimboss** [comment]
Yeah that's fixed on the git version which I have yet to upload to pypi, so use `pip install git+https://github.com/ImNimboss/uberduck.git`

**Comment by ImNimboss** [comment]
I have uploaded the latest version to PyPI, now `pip install uberduck` works for me

**Comment by cool-cose** [comment]
thank you so much
![image](https://user-images.githubusercontent.com/84683778/209344244-61829a1b-e888-48ab-b555-dfc54b1c48c0.png)

**Comment by ImNimboss** [comment]
Glad it worked :>
